### Listado de equipos
GET {{baseUrl}}/api/v1/proyectos HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

### Crear equipo
POST {{baseUrl}}/api/v1/proyectos HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": 0,
  "nombre": "string",
  "descripcion": "string",
  "estado": true,
  "fechaCreacion": "2022-09-27T00:58:48.324Z",
  "creadoPor": "string",
  "fechaModificacion": "2022-09-27T00:58:48.324Z",
  "modificadoPor": "string"
}

### Actualizar equipo
PUT {{baseUrl}}/api/v1/proyectos/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": 0,
  "nombre": "string",
  "descripcion": "string",
  "estado": true,
  "fechaCreacion": "2022-09-27T00:58:48.324Z",
  "creadoPor": "string",
  "fechaModificacion": "2022-09-27T00:58:48.324Z",
  "modificadoPor": "string"
}

### Eliminar equipo
DELETE {{baseUrl}}/api/v1/proyectos/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

